freemodel:
    apikey: ENC[AES256_GCM,data:ZYMMaLT01MDFT3PfWxBzKvUOApcfPnCHtKJM51jrcD0/dm4sp5mN8mdRd8oqpjFfnCXwSVOf,iv:Ibntjez5y77eGKGyL1opsQTBy9TcfBl38VX7zoiGrxY=,tag:w9BmkqPqzKVUFBCVugLkVA==,type:str]
tududi:
    session-secret: ENC[AES256_GCM,data:Ha7029biLFKo3Vd2knuABek9aGmj6cfcIR+gLws3UCdFZ/pLypy2Y1rdSGVF3WYFdGDw+Pez73xeLyeSfaV0w4R6qIdjOCZLSUeM07gRJ6Jt37bKajJCWpNeVw2PkWyrsKQ2cDsXpb/KjNjuijY/d8fSJRQggGJhkzwFQM/gMNQ=,iv:3OJQBTdhgNM4QOD8cUX8iUfkmyN7MmVt0Svuzi6jKXw=,tag:rDj9v+wtD1/qHRPv+3GwrA==,type:str]
    admin-password: ENC[AES256_GCM,data:T8326JHXKuX0vJQg3PPU3BfaPY+Mcs8RITxqWCYWYdh7YRtohzdXRWJHc7Tt3jhA,iv:uQsofGh0Gtfikx9xyplIuyXqHWmrs4SeN/oKY10seyE=,tag:CbtoJvIA5tjzGh/tSrWkcQ==,type:str]
    api-token: ENC[AES256_GCM,data:c0gcdzcc/GK919BDVpOu0NQKGF/+yas8+3V7eFtoemw+R827F44pSFNKWY7ZQRwB46cBJG6USuX6qYGrjLiTMFmnpQ==,iv:BRBLXF8+7hlYp76N+UuORFr4K4MCNOC7OK1fbZtLk5U=,tag:RrWi4ZRbdQUHsjxROHI3qQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNXJvT2hCZVN3eGJhLzI2
            dWNpeEwvOHJORXR0ZjZqa2x6d2pxQk9MU2hVCnpreE5zR1gvZ1A3UFhXQW11NFpE
            Nmk5N0VxMEc4YU44bkVOV044NGdJV00KLS0tIHNZeklBMEFyS3VGU2ZMQXBwMUdx
            anpSQTdQLzQ3U1doUFdpT2R0eS80bUkKvblW1JEIb1zu152gco03+O2vcGq1w+e1
            6U2VMlA8m5PNX8XLokNvPPro/91LlCtLJ7sKDCzCZ37aXzjXljwSvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14nzljj30cme3j7gkkcs27k2h94m5p9lswclc3kclzqcj5nwamqfqcrvs9z
    lastmodified: "2026-08-17T11:29:44Z"
    mac: ENC[AES256_GCM,data:Ve8kgSAtyFDQLf5+sdfiFwgju/3ozM8HSCU7QDL8g0RHFFRYvqpQYZJOr7fAx3nEZAdJK3ImJUYAS0oYUaJBnkJQLmS+EzsGpIh4k+F+FV73UJxZM6PsD5lunEG5shWH6Vm99aK1KbwHrmsay/GLo0QszkwQSb+LOHyTxSXBNmQ=,iv:JI9MyVzouuXsVTpTEm+IVzxFE/FNwJ7r4NgBiSkrad4=,tag:4Iu11T7PH5Do1oaFev4ekg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
