freemodel:
    apikey: ENC[AES256_GCM,data:5Q67kPlqAFkMBc0CT02fn/zHxNDTkv/yHXy+u41bMeZQv+swvg==,iv:sKMT/U+/h0zQclrGxWoJ70nBeMmAc9tMNZVgOBinPtM=,tag:qSqMchS7Sn/gewhCPxWDng==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNXJvT2hCZVN3eGJhLzI2
            dWNpeEwvOHJORXR0ZjZqa2x6d2pxQk9MU2hVCnpreE5zR1gvZ1A3UFhXQW11NFpE
            Nmk5N0VxMEc4YU44bkVOV044NGdJV00KLS0tIHNZeklBMEFyS3VGU2ZMQXBwMUdx
            anpSQTdQLzQ3U1doUFdpT2R0eS80bUkKvblW1JEIb1zu152gco03+O2vcGq1w+e1
            6U2VMlA8m5PNX8XLokNvPPro/91LlCtLJ7sKDCzCZ37aXzjXljwSvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14nzljj30cme3j7gkkcs27k2h94m5p9lswclc3kclzqcj5nwamqfqcrvs9z
    lastmodified: "2026-05-27T12:30:22Z"
    mac: ENC[AES256_GCM,data:CVPssL5kpos8dLXaZwgjvuiA7QC2IbQAEs6wBgB3xDmboOru6k8v5VAp89mf3nWOItsJH7UN0RQsls/iwFpCDPgXQ0Jc30fStg4QTClOwOYLJ0WOqTq65BSbXdGWXKkFQvCwQ+7ecrF3eQ/Eu1n851QNfkzb8giiSHB4639zYVU=,iv:veIwK9GaF2MBOIHdHP3yIl6UacaX6oQwqIAQGuiijU4=,tag:7XhZdUEptzIZd6uPqFBKlw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
