freemodel:
    apikey: ENC[AES256_GCM,data:ZYMMaLT01MDFT3PfWxBzKvUOApcfPnCHtKJM51jrcD0/dm4sp5mN8mdRd8oqpjFfnCXwSVOf,iv:Ibntjez5y77eGKGyL1opsQTBy9TcfBl38VX7zoiGrxY=,tag:w9BmkqPqzKVUFBCVugLkVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNXJvT2hCZVN3eGJhLzI2
            dWNpeEwvOHJORXR0ZjZqa2x6d2pxQk9MU2hVCnpreE5zR1gvZ1A3UFhXQW11NFpE
            Nmk5N0VxMEc4YU44bkVOV044NGdJV00KLS0tIHNZeklBMEFyS3VGU2ZMQXBwMUdx
            anpSQTdQLzQ3U1doUFdpT2R0eS80bUkKvblW1JEIb1zu152gco03+O2vcGq1w+e1
            6U2VMlA8m5PNX8XLokNvPPro/91LlCtLJ7sKDCzCZ37aXzjXljwSvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14nzljj30cme3j7gkkcs27k2h94m5p9lswclc3kclzqcj5nwamqfqcrvs9z
    lastmodified: "2026-05-27T12:48:48Z"
    mac: ENC[AES256_GCM,data:S7nn9EOU3+eFqyjpDsiuPS2DWiCtedbQ8tpfWgJk5W/SZGORBnXMuQCYhkT7+7QNXsxGuawtTp+lnpuQHcl1yjetWdJJRVyUF69dUeOIk1O19Df7nGnhN56BpVVhBGKDevWleWlF3GtsmHBH5vsOfAdrKlP12+nhwKOerEqj+Mw=,iv:OxMqoCXdEXKePUphYZBFJmQl+Zs5F98VB3vSiXbPWic=,tag:dGYPNXZNrZhbJbh9v5QYeA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
